workplace:
  path: /workplace
  methods: [get]
  controller: App\Infrastructure\Interfaces\HttpPort\Action\WorkplaceListAction

reservation:
  path: /reservation
  methods: [get]
  controller: App\Infrastructure\Interfaces\HttpPort\Action\ReservationListAction
